### ISSUE TITLE
Cheraw fault dip inconsistencies

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-fortran#18]
The three Cheraw models that we adopted from the CEUS-SSCn have different dips:

60° CEUScm-recur_2014.in
60° CEUScm-srchar_2014.in
50° CEUScm-srgr_2014.in

@olboyd-usgs is this correct?

**Comment by haller-usgs** [comment]
The Cheraw source in 2008 was assigned the same dip uncertainty as other
normal faults in the model (50±10°); the 60° dip came from the 2002 source
characterization. The 2014 source model used 50±15°. I see no reason why
the Cheraw should be treated differently than any other normal fault.

FYI, the Cheraw was inadvertently included in the geodetic model, and as
such may have had a final weight of 1.2. I don't know how to follow up on
that issue.

**Comment by pmpowers-usgs** [comment]
SSCn Cheraw GR should have a dip of 60°
