### ISSUE TITLE
Makefile:78 recipe for target 'hazSUBX' failed

### ISSUE THREAD

**Issue by SaeedZaman** [usgs/nshmp-haz-fortran#48]
I am trying to compile this repository. I have **MinGW** installed on **Windows 7**. When I run Makefile exits with the following error gfortran : error: src/hazSUBX.f : No such file or directory. 
recipe for target 'hazSUBX' failed 

![error1](https://cloud.githubusercontent.com/assets/17100660/12868414/d70eba86-cd38-11e5-9062-ba7c619cbe55.png)

Any help would be appreciated

**Comment by pmpowers-usgs** [comment]
Some files were updated and renamed to fix bugs but the name changes were not propagated to scripts and makefile. Bear in mind that the makefile commonly needs to tailored to ones local environment and we can offer little in the way of support should any issues arise related to trying to get the codes to run in a Windows environment.

**Comment by pmpowers-usgs** [comment]
The subduction source file was renamed and the makefile updated for consistency. Closed with pr #51
