### ISSUE TITLE
disaggregation

### ISSUE THREAD

**Issue by charlesxwang** [usgs/nshmp-haz-fortran#8]
Hi Mr. Powers, I really like this great repo.
Does this code powers the openSHA web tools, like Hazard Curve Calculator?

I am trying to use openSHA's Hazard Curve Calculator to do a disaggregation.
I can get a nice figure showing the contributions of moment magnitude vs distance.

But I have a simple question: Under what hazard level the disaggregation is done? 
I searched their website and no document was found to my question.

I previously use a similar tool provide by USGS: http://geohazards.usgs.gov/deaggint/2008/
That tool takes a hazard level as input, but Hazard Curve Calculator do not take this input.

...
I'll appreciate any of your hint.
![hazard](https://cloud.githubusercontent.com/assets/8227254/10383920/27b5f728-6e03-11e5-900a-59526e3f6282.PNG)

**Comment by pmpowers-usgs** [comment]
Hi Happy,

You're mixing two separate codebases here. This repository hosts the fortran codes that were used to compute the previous (2008) and current (2014) versions of the USGS National Seismic hazard map. The USGS website has web applications that can perform deaggregations of the 2008 and prior models, but not the 2014 model, yet. This is coming soon. The codes in this repository can not be used to compute deaggregations, just hazard. I see you also commented via the OpenSHA website, the code from which the figure you posted was generated and I will respond to that separately.

Peter
